// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings is persisted to ~/Documents/StoryEngine/app.json.
 * APIKey is empty for local models (Ollama, LM Studio).
 */
export class AppSettings {
    "llmEndpoint": string;
    "llmModel": string;
    "llmApiKey": string;
    "lastProjectPath": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("llmEndpoint" in $$source)) {
            this["llmEndpoint"] = "";
        }
        if (!("llmModel" in $$source)) {
            this["llmModel"] = "";
        }
        if (!("llmApiKey" in $$source)) {
            this["llmApiKey"] = "";
        }
        if (!("lastProjectPath" in $$source)) {
            this["lastProjectPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * CharacterProfile is one entry in the project-wide character roster.
 */
export class CharacterProfile {
    "name": string;

    /**
     * LLM-generated
     */
    "description": string;

    /**
     * scene IDs
     */
    "appearsIn": string[];
    "updatedAt": number;

    /** Creates a new CharacterProfile instance. */
    constructor($$source: Partial<CharacterProfile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("appearsIn" in $$source)) {
            this["appearsIn"] = [];
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): CharacterProfile {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearsIn" in $$parsedSource) {
            $$parsedSource["appearsIn"] = $$createField2_0($$parsedSource["appearsIn"]);
        }
        return new CharacterProfile($$parsedSource as Partial<CharacterProfile>);
    }
}

/**
 * ChatMessage is one turn in the project chat history.
 */
export class ChatMessage {
    /**
     * "user" | "assistant"
     */
    "role": string;
    "content": string;

    /**
     * populated for assistant messages
     */
    "sources"?: SceneSource[];

    /** Creates a new ChatMessage instance. */
    constructor($$source: Partial<ChatMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessage {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField2_0($$parsedSource["sources"]);
        }
        return new ChatMessage($$parsedSource as Partial<ChatMessage>);
    }
}

/**
 * ChatResponse is returned by the AskQuestion IPC method.
 */
export class ChatResponse {
    "answer": string;
    "sources": SceneSource[];

    /** Creates a new ChatResponse instance. */
    constructor($$source: Partial<ChatResponse> = {}) {
        if (!("answer" in $$source)) {
            this["answer"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatResponse {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField1_0($$parsedSource["sources"]);
        }
        return new ChatResponse($$parsedSource as Partial<ChatResponse>);
    }
}

/**
 * ProjectInfo is returned by GetProjects and GetCurrentProject.
 */
export class ProjectInfo {
    "name": string;
    "path": string;
    "createdAt": number;

    /** Creates a new ProjectInfo instance. */
    constructor($$source: Partial<ProjectInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectInfo($$parsedSource as Partial<ProjectInfo>);
    }
}

/**
 * Scene is a cache record. FilePath points to the authoritative .md file.
 */
export class Scene {
    "id": string;
    "title": string;
    "filePath": string;
    "orderIndex": number;
    "wordCount": number;
    "lastModified": number;
    "cursorPosition": number;
    "scrollTop": number;

    /** Creates a new Scene instance. */
    constructor($$source: Partial<Scene> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("orderIndex" in $$source)) {
            this["orderIndex"] = 0;
        }
        if (!("wordCount" in $$source)) {
            this["wordCount"] = 0;
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = 0;
        }
        if (!("cursorPosition" in $$source)) {
            this["cursorPosition"] = 0;
        }
        if (!("scrollTop" in $$source)) {
            this["scrollTop"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scene instance from a string or object.
     */
    static createFrom($$source: any = {}): Scene {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Scene($$parsedSource as Partial<Scene>);
    }
}

/**
 * SceneInsights is returned by GetSceneInsights for the Mirror panel on scene switch.
 */
export class SceneInsights {
    "sceneId": string;

    /**
     * may be empty if not yet generated
     */
    "summary": string;

    /** Creates a new SceneInsights instance. */
    constructor($$source: Partial<SceneInsights> = {}) {
        if (!("sceneId" in $$source)) {
            this["sceneId"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SceneInsights instance from a string or object.
     */
    static createFrom($$source: any = {}): SceneInsights {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SceneInsights($$parsedSource as Partial<SceneInsights>);
    }
}

/**
 * SceneSource is a ranked scene reference in a chat response.
 */
export class SceneSource {
    "sceneId": string;
    "title": string;
    "score": number;

    /** Creates a new SceneSource instance. */
    constructor($$source: Partial<SceneSource> = {}) {
        if (!("sceneId" in $$source)) {
            this["sceneId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SceneSource instance from a string or object.
     */
    static createFrom($$source: any = {}): SceneSource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SceneSource($$parsedSource as Partial<SceneSource>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SceneSource.createFrom;
const $$createType2 = $Create.Array($$createType1);
