// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings stores LLM configuration. Persisted to ~/Documents/StoryEngine/settings.json.
 * APIKey is optional — leave empty for local models (Ollama, LM Studio).
 */
export class AppSettings {
    /**
     * e.g. "http://localhost:11434/v1"
     */
    "llmEndpoint": string;

    /**
     * e.g. "llama3.2:3b"
     */
    "llmModel": string;

    /**
     * empty for local; required for OpenAI/Groq
     */
    "llmApiKey": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("llmEndpoint" in $$source)) {
            this["llmEndpoint"] = "";
        }
        if (!("llmModel" in $$source)) {
            this["llmModel"] = "";
        }
        if (!("llmApiKey" in $$source)) {
            this["llmApiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * Scene represents a single writing scene.
 */
export class Scene {
    "id": string;
    "title": string;
    "filePath": string;
    "orderIndex": number;
    "wordCount": number;
    "lastModified": number;
    "cursorPosition": number;
    "scrollTop": number;

    /** Creates a new Scene instance. */
    constructor($$source: Partial<Scene> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("orderIndex" in $$source)) {
            this["orderIndex"] = 0;
        }
        if (!("wordCount" in $$source)) {
            this["wordCount"] = 0;
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = 0;
        }
        if (!("cursorPosition" in $$source)) {
            this["cursorPosition"] = 0;
        }
        if (!("scrollTop" in $$source)) {
            this["scrollTop"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scene instance from a string or object.
     */
    static createFrom($$source: any = {}): Scene {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Scene($$parsedSource as Partial<Scene>);
    }
}

/**
 * SceneInsights is returned by GetInsights when loading a scene.
 * InteractionsJSON is a raw JSON string to avoid re-encoding complexity at the IPC boundary.
 */
export class SceneInsights {
    "sceneId": string;
    "entities": string[];
    "interactionsJSON": string;
    "sceneTone": string;
    "source": string;
    "wordCount": number;

    /** Creates a new SceneInsights instance. */
    constructor($$source: Partial<SceneInsights> = {}) {
        if (!("sceneId" in $$source)) {
            this["sceneId"] = "";
        }
        if (!("entities" in $$source)) {
            this["entities"] = [];
        }
        if (!("interactionsJSON" in $$source)) {
            this["interactionsJSON"] = "";
        }
        if (!("sceneTone" in $$source)) {
            this["sceneTone"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("wordCount" in $$source)) {
            this["wordCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SceneInsights instance from a string or object.
     */
    static createFrom($$source: any = {}): SceneInsights {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entities" in $$parsedSource) {
            $$parsedSource["entities"] = $$createField1_0($$parsedSource["entities"]);
        }
        return new SceneInsights($$parsedSource as Partial<SceneInsights>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
