// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Scene represents a single writing scene.
 * It is a cache record — the FilePath field points to the authoritative .md file.
 * Deleting this record does not delete the file.
 */
export class Scene {
    "id": string;
    "title": string;

    /**
     * relative to project ScenesDir
     */
    "filePath": string;
    "orderIndex": number;
    "wordCount": number;

    /**
     * Unix timestamp
     */
    "lastModified": number;

    /**
     * CodeMirror offset
     */
    "cursorPosition": number;

    /**
     * pixels, from scrollDOM
     */
    "scrollTop": number;

    /** Creates a new Scene instance. */
    constructor($$source: Partial<Scene> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("orderIndex" in $$source)) {
            this["orderIndex"] = 0;
        }
        if (!("wordCount" in $$source)) {
            this["wordCount"] = 0;
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = 0;
        }
        if (!("cursorPosition" in $$source)) {
            this["cursorPosition"] = 0;
        }
        if (!("scrollTop" in $$source)) {
            this["scrollTop"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scene instance from a string or object.
     */
    static createFrom($$source: any = {}): Scene {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Scene($$parsedSource as Partial<Scene>);
    }
}

/**
 * SceneInsights is the full insights payload returned by GetInsights.
 * It combines entity data from SQLite with the current word count.
 */
export class SceneInsights {
    "sceneId": string;

    /**
     * candidate character names
     */
    "entities": string[];

    /**
     * estimated dialogue segments
     */
    "dialogueCount": number;
    "wordCount": number;

    /** Creates a new SceneInsights instance. */
    constructor($$source: Partial<SceneInsights> = {}) {
        if (!("sceneId" in $$source)) {
            this["sceneId"] = "";
        }
        if (!("entities" in $$source)) {
            this["entities"] = [];
        }
        if (!("dialogueCount" in $$source)) {
            this["dialogueCount"] = 0;
        }
        if (!("wordCount" in $$source)) {
            this["wordCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SceneInsights instance from a string or object.
     */
    static createFrom($$source: any = {}): SceneInsights {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entities" in $$parsedSource) {
            $$parsedSource["entities"] = $$createField1_0($$parsedSource["entities"]);
        }
        return new SceneInsights($$parsedSource as Partial<SceneInsights>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
