import { useEffect, useRef, useCallback } from 'react'
import { EditorView, keymap } from '@codemirror/view'
import { EditorState } from '@codemirror/state'
import { defaultKeymap, history, historyKeymap } from '@codemirror/commands'
import { markdown } from '@codemirror/lang-markdown'
import { useSceneStore } from '../state/sceneStore'
import { useEditorStore } from '../state/editorStore'


// IPC bindings auto-generated by Wails v3. Import paths may vary depending on
// the version of Wails used. Check wailsjs/ after running wails3 dev.
// Adjust the import path if the generated file is at a different location.
import { SaveSceneContent, SaveCursorState, GetSceneContent, GetInsights } from '../../bindings/story-engine/app'
import { useInsightsStore } from '../state/insightsStore'

// ─── CodeMirror Stone Theme ────────────────────────────────────────────────

const stoneTheme = EditorView.theme(
  {
    '&': {
      backgroundColor: '#1B1B1B',
      color: '#D1D1D1',
      height: '100%',
      fontFamily: 'Georgia, Cambria, "Times New Roman", serif',
      fontSize: '17px',
    },
    '.cm-content': {
      padding: '64px 0',
      maxWidth: '680px',
      margin: '0 auto',
      caretColor: '#D1D1D1',
      lineHeight: '1.85',
    },
    '.cm-line': { padding: '0 24px' },
    '.cm-cursor, .cm-dropCursor': {
      borderLeftColor: '#D1D1D1',
      borderLeftWidth: '1.5px',
    },
    '&.cm-focused .cm-selectionBackground, .cm-selectionBackground': {
      backgroundColor: '#2E2E2E !important',
    },
    '.cm-scroller': { overflowY: 'auto', fontFamily: 'inherit' },
    '.cm-gutters': { display: 'none' },
  },
  { dark: true }
)

// ─── useEditor Hook ─────────────────────────────────────────────────────────

export function useEditor() {
  const containerRef = useRef<HTMLDivElement>(null)
  const viewRef = useRef<EditorView | null>(null)
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const currentSceneIdRef = useRef<string | null>(null)

  const updateScene = useSceneStore((s) => s.updateScene)
  const setInsights = useInsightsStore((s) => s.setInsights)
  const setSaveState = useEditorStore((s) => s.setSaveState)

  // ── Save cursor state for a scene before leaving it ──────────────────────
  const saveCursorState = useCallback(async (id: string) => {
    const view = viewRef.current
    if (!view) return
    const pos = view.state.selection.main.anchor
    const scrollTop = view.scrollDOM.scrollTop
    try {
      await SaveCursorState(id, pos, scrollTop)
    } catch (err) {
      console.error('[Story Engine] SaveCursorState failed:', err)
    }
  }, [])

  // ── Load a scene into the editor ─────────────────────────────────────────
  const loadScene = useCallback(
    async (id: string, cursorPos: number, scrollTop: number) => {
      const view = viewRef.current
      if (!view) return

      // Clear any pending debounced save for the old scene.
      if (debounceRef.current) {
        clearTimeout(debounceRef.current)
        debounceRef.current = null
      }

      currentSceneIdRef.current = id

      // Clear the editor first to avoid stale cursor-range errors.
      view.dispatch({
        changes: { from: 0, to: view.state.doc.length, insert: '' },
      })

      // Fetch scene content from the file system via IPC.
      let content = ''
      try {
        content = await GetSceneContent(id)
      } catch (err) {
        console.error('[Story Engine] GetSceneContent failed:', err)
      }

      // Replace document with new content.
      view.dispatch({
        changes: { from: 0, to: view.state.doc.length, insert: content },
      })

      // Restore cursor position (clamp to document length for safety).
      const safePos = Math.min(cursorPos, view.state.doc.length)
      view.dispatch({ selection: { anchor: safePos } })

      // Restore scroll position on the next animation frame.
      requestAnimationFrame(() => {
        if (viewRef.current) {
          viewRef.current.scrollDOM.scrollTop = scrollTop
        }
      })

      view.focus()

      // Load last-known insights for this scene.
      try {
        const insights = await GetInsights(id)
        setInsights({
          sceneId: insights.sceneId,
          entities: insights.entities ?? [],
          dialogueCount: insights.dialogueCount ?? 0,
        })
      } catch (err) {
        console.error('[Story Engine] GetInsights failed:', err)
      }
    },
    [setInsights]
  )

  // ── Create the EditorView on mount ───────────────────────────────────────
  useEffect(() => {
    if (!containerRef.current) return

    const updateListener = EditorView.updateListener.of((update) => {
      if (!update.docChanged) return
      const id = currentSceneIdRef.current
      if (!id) return

      // Debounce the save: 800ms of silence triggers a write.
      if (debounceRef.current) clearTimeout(debounceRef.current)
      setSaveState('saving')  // ← immediately mark as saving when timer is set
      debounceRef.current = setTimeout(async () => {
        const content = update.state.doc.toString()
        try {
          await SaveSceneContent(id, content)
          const wordCount = content.trim() === '' ? 0 : content.trim().split(/\s+/).length
          updateScene(id, { wordCount })
          setSaveState('saved')  // ← mark saved on success
          // Fade back to idle after 2 seconds
          setTimeout(() => setSaveState('idle'), 2000)
        } catch (err) {
          console.error('[Story Engine] SaveSceneContent failed:', err)
          setSaveState('idle')
        }
      }, 800)
    })

    const state = EditorState.create({
      doc: '',
      extensions: [
        history(),
        markdown(),
        EditorView.lineWrapping,
        stoneTheme,
        keymap.of([...defaultKeymap, ...historyKeymap]),
        updateListener,
      ],
    })

    const view = new EditorView({ state, parent: containerRef.current })
    viewRef.current = view

    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current)
      view.destroy()
      viewRef.current = null
    }
  }, [updateScene])

  return { containerRef, loadScene, saveCursorState }
}