// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the IPC coordinator. It owns all services and exposes methods to the
 * frontend. Initialize() must be called from main.go before app.Run().
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

export function CreateScene(title: string): $CancellablePromise<models$0.Scene> {
    return $Call.ByID(2007345907, title).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteScene(id: string): $CancellablePromise<void> {
    return $Call.ByID(3853166994, id);
}

export function GetInsights(sceneID: string): $CancellablePromise<models$0.SceneInsights> {
    return $Call.ByID(3201157490, sceneID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSceneContent(id: string): $CancellablePromise<string> {
    return $Call.ByID(1384012906, id);
}

export function GetScenes(): $CancellablePromise<models$0.Scene[]> {
    return $Call.ByID(1439475674).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Initialize sets up all services. It is called from main.go before app.Run()
 * so that every service is ready before the WebView loads. This avoids any
 * race between Wails service lifecycle timing and the frontend's first IPC call.
 */
export function Initialize(win: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(2338951747, win);
}

/**
 * OnShutdown is called by Wails when the application closes.
 */
export function OnShutdown(): $CancellablePromise<void> {
    return $Call.ByID(999779538);
}

export function RenameScene(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(3125356185, id, title);
}

export function ReorderScene(id: string, newIndex: number): $CancellablePromise<void> {
    return $Call.ByID(3339165816, id, newIndex);
}

export function SaveCursorState(id: string, cursorPos: number, scrollTop: number): $CancellablePromise<void> {
    return $Call.ByID(3711121783, id, cursorPos, scrollTop);
}

export function SaveSceneContent(id: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3606472253, id, content);
}

// Private type creation functions
const $$createType0 = models$0.Scene.createFrom;
const $$createType1 = models$0.SceneInsights.createFrom;
const $$createType2 = $Create.Array($$createType0);
