// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the IPC coordinator. Initialize() must be called from main.go before app.Run().
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * AnalyzeProject calls the LLM with excerpts from all scenes to build/update
 * the project-wide character roster. This is the 🧠 button at the project level.
 */
export function AnalyzeProject(): $CancellablePromise<void> {
    return $Call.ByID(1224075352);
}

/**
 * AnalyzeScene generates or regenerates the summary for a specific scene.
 */
export function AnalyzeScene(sceneID: string): $CancellablePromise<void> {
    return $Call.ByID(2052825417, sceneID);
}

/**
 * AskQuestion answers a question about the project using keyword-ranked scene context.
 */
export function AskQuestion(question: string): $CancellablePromise<models$0.ChatResponse> {
    return $Call.ByID(1524600290, question).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BatchReorderScenes replaces the old ReorderScene. Takes the full ordered slice
 * of scene IDs and assigns sequential order indices in a single transaction.
 */
export function BatchReorderScenes(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2511860427, orderedIDs);
}

/**
 * ClearChat clears the project chat history.
 */
export function ClearChat(): $CancellablePromise<void> {
    return $Call.ByID(4193536212);
}

/**
 * CreateProject creates a new project directory and loads it.
 */
export function CreateProject(name: string): $CancellablePromise<models$0.ProjectInfo> {
    return $Call.ByID(969543070, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateScene(title: string): $CancellablePromise<models$0.Scene> {
    return $Call.ByID(2007345907, title).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteScene(id: string): $CancellablePromise<void> {
    return $Call.ByID(3853166994, id);
}

/**
 * GetCharacters returns the project-wide character roster from mirror/characters.json.
 */
export function GetCharacters(): $CancellablePromise<{ [_ in string]?: models$0.CharacterProfile }> {
    return $Call.ByID(4260071327).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetChatHistory returns the project chat history.
 */
export function GetChatHistory(): $CancellablePromise<models$0.ChatMessage[]> {
    return $Call.ByID(3791931187).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetCurrentProject returns metadata about the loaded project.
 */
export function GetCurrentProject(): $CancellablePromise<models$0.ProjectInfo> {
    return $Call.ByID(2444786021).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProjects scans ~/Documents/StoryEngine/ for project directories.
 */
export function GetProjects(): $CancellablePromise<models$0.ProjectInfo[]> {
    return $Call.ByID(540785005).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSceneContent(id: string): $CancellablePromise<string> {
    return $Call.ByID(1384012906, id);
}

/**
 * GetSceneInsights returns the stored summary for a scene from mirror/scenes/<id>.json.
 */
export function GetSceneInsights(sceneID: string): $CancellablePromise<models$0.SceneInsights> {
    return $Call.ByID(3562086736, sceneID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetScenes(): $CancellablePromise<models$0.Scene[]> {
    return $Call.ByID(1439475674).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetSettings returns the current app settings.
 */
export function GetSettings(): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Initialize is called from main.go before app.Run().
 */
export function Initialize(win: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(2338951747, win);
}

export function OnShutdown(): $CancellablePromise<void> {
    return $Call.ByID(999779538);
}

export function RenameScene(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(3125356185, id, title);
}

export function SaveCursorState(id: string, cursorPos: number, scrollTop: number): $CancellablePromise<void> {
    return $Call.ByID(3711121783, id, cursorPos, scrollTop);
}

/**
 * SaveSceneContent writes the scene to disk, updates word count, and triggers
 * analysis. If the scene's word count has grown by ≥100 since the last LLM
 * analysis, a background scene summary regeneration is triggered automatically.
 */
export function SaveSceneContent(id: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3606472253, id, content);
}

/**
 * SaveSettings persists settings and hot-swaps the LLM configuration.
 */
export function SaveSettings(settings: models$0.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1949631069, settings);
}

/**
 * SwitchProject switches to an existing project and returns its scene list.
 */
export function SwitchProject(projectPath: string): $CancellablePromise<models$0.Scene[]> {
    return $Call.ByID(2353779634, projectPath).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.ChatResponse.createFrom;
const $$createType1 = models$0.ProjectInfo.createFrom;
const $$createType2 = models$0.Scene.createFrom;
const $$createType3 = models$0.CharacterProfile.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = models$0.ChatMessage.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType1);
const $$createType8 = models$0.SceneInsights.createFrom;
const $$createType9 = $Create.Array($$createType2);
const $$createType10 = models$0.AppSettings.createFrom;
