// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class WebviewWindow {

    /** Creates a new WebviewWindow instance. */
    constructor($$source: Partial<WebviewWindow> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebviewWindow instance from a string or object.
     */
    static createFrom($$source: any = {}): WebviewWindow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebviewWindow($$parsedSource as Partial<WebviewWindow>);
    }
}
